import base64
import os
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import encoders

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


def _get_service():
    credentials_file = os.getenv("GMAIL_CREDENTIALS_FILE", "credentials.json")
    token_file       = os.getenv("GMAIL_TOKEN_FILE", "token.json")
    creds = None

    if os.path.exists(token_file):
        creds = Credentials.from_authorized_user_file(token_file, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(credentials_file):
                raise FileNotFoundError(
                    f"{credentials_file} not found.\n"
                    "Download it from Google Cloud Console → APIs & Services → Credentials.\n"
                    "Then run: python setup_gmail.py"
                )
            flow = InstalledAppFlow.from_client_secrets_file(credentials_file, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(token_file, "w") as f:
            f.write(creds.to_json())

    return build("gmail", "v1", credentials=creds)


def _build_plain_body(scraper: str, record_count: int, city: str, date_str: str,
                      qualifications: list, company_name: str) -> str:
    sources = " + ".join(s.capitalize() for s in scraper.split("+")) if "+" in scraper else scraper.capitalize()
    quals   = ", ".join(qualifications) if qualifications else "N/A"
    return (
        f"{company_name}\n"
        f"{'─' * 40}\n"
        f"Job Market Report\n\n"
        f"Source      : {sources}\n"
        f"City        : {city}\n"
        f"Total Jobs  : {record_count}\n"
        f"Qualifications: {quals}\n"
        f"Generated   : {date_str}\n\n"
        f"Please find the full Excel report attached.\n\n"
        f"── Generated by AIWORKFLOW · {company_name} ──"
    )


def _build_html_body(scraper: str, record_count: int, city: str, date_str: str,
                     qualifications: list, company_name: str, has_logo: bool) -> str:
    sources = " + ".join(s.capitalize() for s in scraper.split("+")) if "+" in scraper else scraper.capitalize()
    quals   = ", ".join(qualifications) if qualifications else "N/A"
    logo_html = (
        '<img src="cid:netnova_logo" alt="Logo" '
        'style="height:48px;max-width:160px;object-fit:contain;display:block;">'
        if has_logo else ""
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#F0F2F5;font-family:Calibri,Arial,sans-serif;">

  <!-- Wrapper -->
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F0F2F5;padding:32px 0;">
    <tr><td align="center">
      <table width="620" cellpadding="0" cellspacing="0"
             style="background:#ffffff;border-radius:10px;overflow:hidden;
                    box-shadow:0 4px 20px rgba(0,0,0,0.10);">

        <!-- ── Header ── -->
        <tr>
          <td style="background:#1B2A4A;padding:20px 28px;">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td style="vertical-align:middle;width:50%;">
                  {logo_html}
                </td>
                <td align="right" style="vertical-align:middle;">
                  <span style="color:#ffffff;font-size:15px;font-weight:600;
                               letter-spacing:0.4px;">{company_name}</span>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- ── Gold accent bar ── -->
        <tr>
          <td style="background:#F5A623;height:4px;font-size:0;line-height:0;">&nbsp;</td>
        </tr>

        <!-- ── Title ── -->
        <tr>
          <td style="padding:28px 28px 8px 28px;">
            <p style="margin:0;font-size:22px;font-weight:700;color:#1B2A4A;">
              Job Market Report
            </p>
            <p style="margin:6px 0 0;font-size:13px;color:#888888;">
              Generated on {date_str}
            </p>
          </td>
        </tr>

        <!-- ── Stats cards ── -->
        <tr>
          <td style="padding:20px 28px;">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <!-- Source -->
                <td width="32%" style="background:#F7F8FA;border:1px solid #E8EBF0;
                            border-radius:8px;padding:14px 12px;text-align:center;">
                  <p style="margin:0;font-size:11px;color:#888;text-transform:uppercase;
                             letter-spacing:0.6px;">Source</p>
                  <p style="margin:6px 0 0;font-size:18px;font-weight:700;color:#1B2A4A;">
                    {sources}
                  </p>
                </td>
                <td width="4%"></td>
                <!-- Jobs Found -->
                <td width="32%" style="background:#1B2A4A;border-radius:8px;
                            padding:14px 12px;text-align:center;">
                  <p style="margin:0;font-size:11px;color:#F5A623;text-transform:uppercase;
                             letter-spacing:0.6px;">Jobs Found</p>
                  <p style="margin:6px 0 0;font-size:28px;font-weight:700;color:#ffffff;">
                    {record_count}
                  </p>
                </td>
                <td width="4%"></td>
                <!-- City -->
                <td width="32%" style="background:#F7F8FA;border:1px solid #E8EBF0;
                            border-radius:8px;padding:14px 12px;text-align:center;">
                  <p style="margin:0;font-size:11px;color:#888;text-transform:uppercase;
                             letter-spacing:0.6px;">City</p>
                  <p style="margin:6px 0 0;font-size:18px;font-weight:700;color:#1B2A4A;">
                    {city}
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- ── Qualifications ── -->
        <tr>
          <td style="padding:0 28px 20px;">
            <table width="100%" cellpadding="0" cellspacing="0"
                   style="background:#FFF8EC;border-left:4px solid #F5A623;border-radius:4px;">
              <tr>
                <td style="padding:12px 16px;">
                  <p style="margin:0;font-size:12px;color:#888;text-transform:uppercase;
                             letter-spacing:0.5px;">Filtered by Qualifications</p>
                  <p style="margin:4px 0 0;font-size:14px;font-weight:600;color:#1B2A4A;">
                    {quals}
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- ── Body text ── -->
        <tr>
          <td style="padding:0 28px 24px;">
            <p style="margin:0;font-size:14px;color:#444;line-height:1.7;">
              Hi,<br><br>
              Please find the full <strong>Excel report</strong> attached to this email.
              It contains a <strong>Dashboard</strong>, complete <strong>Jobs</strong> listing
              with recruiter details, and <strong>Charts</strong> for each source.
            </p>
          </td>
        </tr>

        <!-- ── Attachment note ── -->
        <tr>
          <td style="padding:0 28px 28px;">
            <table cellpadding="0" cellspacing="0">
              <tr>
                <td style="background:#1B2A4A;border-radius:6px;padding:12px 24px;">
                  <span style="color:#ffffff;font-size:13px;font-weight:600;">
                    📎 &nbsp;Excel Report Attached
                  </span>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- ── Divider ── -->
        <tr>
          <td style="padding:0 28px;">
            <hr style="border:none;border-top:1px solid #E8EBF0;margin:0;">
          </td>
        </tr>

        <!-- ── Footer ── -->
        <tr>
          <td style="padding:16px 28px;text-align:center;">
            <p style="margin:0;font-size:11px;color:#AAAAAA;line-height:1.6;">
              Generated by <strong>AIWORKFLOW</strong>
              &nbsp;·&nbsp; {company_name}
              &nbsp;·&nbsp; {date_str}
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>

</body>
</html>"""


def send_email(attachment_path: str, config: dict, record_count: int, city: str = ""):
    from datetime import datetime

    recipient = os.getenv("GMAIL_RECIPIENT", "").strip()
    if not recipient:
        raise ValueError(
            "GMAIL_RECIPIENT is not set. Add it to your .env file:\n"
            "  GMAIL_RECIPIENT=you@example.com"
        )

    company_name  = os.getenv("COMPANY_NAME", "Netnova Tech Company")
    logo_path     = os.getenv("COMPANY_LOGO", "log.png")
    has_logo      = os.path.exists(logo_path)
    date_str      = datetime.now().strftime("%B %d, %Y  %H:%M")
    scraper       = config.get("scraper", "unknown")
    qualifications = config.get("qualifications", [])

    email_cfg = config.get("email", {})
    subject   = (
        email_cfg.get("subject", "Job Listings Report — {date}")
        .replace("{date}", datetime.now().strftime("%Y-%m-%d"))
        .replace("{scraper}", scraper.capitalize())
    )

    # ── Build MIME structure ────────────────────────────────────────────────
    outer = MIMEMultipart("mixed")
    outer["To"]      = recipient
    outer["Subject"] = f"{company_name} | {subject}"

    # HTML + plain-text alternative block
    related = MIMEMultipart("related")
    alternative = MIMEMultipart("alternative")

    plain_body = _build_plain_body(scraper, record_count, city, date_str, qualifications, company_name)
    html_body  = _build_html_body(scraper, record_count, city, date_str, qualifications, company_name, has_logo)

    alternative.attach(MIMEText(plain_body, "plain"))
    alternative.attach(MIMEText(html_body, "html"))
    related.attach(alternative)

    # Inline logo
    if has_logo:
        with open(logo_path, "rb") as f:
            logo_img = MIMEImage(f.read())
        logo_img.add_header("Content-ID", "<netnova_logo>")
        logo_img.add_header("Content-Disposition", "inline", filename=os.path.basename(logo_path))
        related.attach(logo_img)

    outer.attach(related)

    # Excel attachment
    excel_filename = os.path.basename(attachment_path)
    with open(attachment_path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f'attachment; filename="{excel_filename}"')
    outer.attach(part)

    # ── Send ───────────────────────────────────────────────────────────────
    raw = base64.urlsafe_b64encode(outer.as_bytes()).decode()
    service = _get_service()
    service.users().messages().send(userId="me", body={"raw": raw}).execute()
    print(f"[gmail] Email sent to {recipient} — {excel_filename}")
